apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkding

resources:
  - namespace.yaml
  - service-accounts.yaml
  - secrets.yaml
  - pvcs.yaml
  - postgres-config.yaml
  - postgres.yaml
  - deployment.yaml
  - httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: linkding
    includeSelectors: false

images:
  - name: sissbruecker/linkding
    newTag: 1.44.1
  - name: postgres
    newTag: 16-alpine
